.TH HIGHCAL 1 "June 2012" "highcal" "Highlight dates in a calendar"
.SH NAME
highcal \- highlight dates in a calendar.
.SH SYNOPSIS
\fBhighcal\fP
.SH DESCRIPTION
Create calendars like \fBcal\fP(1) but optionally highlight some days.
Feed this script a list of days on \fBstdin\fP, one day per line:
.P
\f(CW
.nf
	$ ./highcal <<EOF
	2011-10-16
	2011-07-08
	EOF
.fi
\fP
.P
The current month will be shown plus the two following months. The
script will highlight the dates from \fBstdin\fP.
.P
\fBhighcal\fP requires \fBtput\fP(1) in order to set colors.
.SH OPTIONS
\fBhighcal\fP does not know any options.
.SH BUGS
Currently, no bugs are known. If you find one, we invite you to report
it at the GitHub Issue tracker (http://github.com/vain/gitodo/issues).
.SH LICENSE
\fBhighcal\fP is released as \(lqPIZZA-WARE\(rq. See the accompanying
\fILICENSE\fP file.
.SH HISTORY
\fBgitodo\fP was originally written by Peter Hofmann. The project was
started in December 2010. \fBhighcal\fP was added in October 2011.
.SH "SEE ALSO"
.BR gitodo (1),
.BR git (1),
.BR tput (1).
