.TH HIGHCAL 1 "March 2014" "highcal" "Highlight dates in a calendar"
.SH NAME
highcal \- highlight dates in a calendar
.SH SYNOPSIS
\fBhighcal\fP [\fIyear\fP]
.SH DESCRIPTION
Create calendars similar to \fBcal\fP(1) but optionally highlight some
days. Feed this script a list of days on \fBstdin\fP, one day per line:
.P
\f(CW
.nf
    $ ./highcal <<EOF
    2011-10-16
    2011-07-08
    EOF
.fi
\fP
.P
If \fBstdin\fP is a terminal, \fBhighcal\fP will not read any dates.
This allows you to simply call \fBhighcal\fP like you call \fBcal\fP.
.SH OPTIONS
If \fIyear\fP is given, \fBhighcal\fP will print the calender for the
whole year. Otherwise, the current month will be shown plus the two
following months. If \fIyear\fP is a string that can't be converted to
an integer, the current year will be used instead.
.SH ENVIRONMENT
.TP
.PD 0
.B HIGHCAL_FORCE_COLOR
.TP
.B GITODO_FORCE_COLOR
If either of these variables are set, color is used in any case, even if
stdout is not a terminal.
.PD
.SH BUGS
Currently, no bugs are known. If you find one, we invite you to report
it at the GitHub Issue tracker (http://github.com/vain/gitodo/issues).
.SH LICENSE
\fBhighcal\fP is released under the MIT license. See the accompanying
\fILICENSE\fP file.
.SH HISTORY
\fBgitodo\fP was originally written by Peter Hofmann. The project was
started in December 2010. \fBhighcal\fP was added in October 2011.
.SH "SEE ALSO"
.BR gitodo (1),
.BR git (1),
.BR ruby (1).
